# app config
spring.application.name=Task_Organized_System_back_end

# database
spring.datasource.url=your_db_url
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# mail
spring.mail.host=smtp.163.com
spring.mail.port=465
spring.mail.username=your_emial@163.com
spring.mail.password=your SMTP authorization code
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
spring.mail.default-encoding=UTF-8

# file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# security debug (dev only)
logging.level.org.springframework.security=DEBUG

# server config
server.address=0.0.0.0
server.port=8081