# ???config
spring.application.name=Task_Organized_System_back_end
spring.datasource.url=jdbc:postgresql://localhost:5432/teamproject
spring.datasource.username=postgres
spring.datasource.password=zjs050124
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ????config
spring.mail.host=smtp.163.com
spring.mail.port=465
spring.mail.username=task_organized_sys@163.com
spring.mail.password=MHgAQipWJCW7ni44
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8

# ?? multipart ??
spring.servlet.multipart.enabled=true

# ????????????????????????????????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=DEBUG

